apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    appInstance: lanchonetwsapp
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgresql
    appInstance: lanchonetwsapp
