name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - develop  # Escolha as branches que deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # Configurar o Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Altere para a versão do Terraform que você utiliza

    # Inicializar o Terraform
    - name: Terraform Init
      run: terraform init

    # Aplicar as mudanças com o Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve

    # Logar no Docker Hub (caso utilize imagens no Docker Hub)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir e enviar a imagem Docker
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/lanchonete-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/lanchonete-app:latest

    # Aplicar as configurações no Kubernetes usando kubectl
    - name: Deploy to Kubernetes
      uses: appleboy/k8s-action@v0.0.21
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        namespace: default  # Defina o namespace correto
        manifests: |
          ./kubernetes-chart/deployment.yml
          ./kubernetes-chart/service.yml

